# Generated by Django 5.1.7 on 2025-05-04 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=100, null=True)),
                ('function', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaturaSubject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('level', models.CharField(choices=[('PD', 'podstawowy'), ('ROZ', 'rozszerzony')], default='ROZ', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('surname', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('color', models.CharField(max_length=300)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('recurrent', models.BooleanField(default=False)),
                ('recurrency_details', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.building')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('formula', models.CharField(default='', max_length=1000)),
                ('type', models.CharField(choices=[('STACJONARNE', 'for all users'), ('NIESTACJONARNE', 'for me and my group-mates')], default='stacjonarne', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('specialization', models.CharField(blank=True, max_length=300, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.faculty')),
                ('G1_subject', models.ManyToManyField(blank=True, related_name='G1', to='mainApp.maturasubject')),
                ('G2_subject', models.ManyToManyField(blank=True, related_name='G2', to='mainApp.maturasubject')),
            ],
        ),
        migrations.CreateModel(
            name='FieldByYear',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.field')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('code', models.CharField(default='lFz9leck7fL81cla9srGHxUEGGHmi8mZ', max_length=300)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fieldByYear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.fieldbyyear')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('isRead', models.BooleanField(default=False)),
                ('message', models.CharField(max_length=1000)),
                ('time_triggered', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('min_threshold', models.IntegerField(default=0)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.field')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('ECTS_required', models.IntegerField(default=30)),
                ('field_by_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.fieldbyyear')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('ECTS', models.IntegerField(default=1)),
                ('test_type', models.CharField(default='egzamin', max_length=300)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('lecturer', models.CharField(blank=True, max_length=300, null=True)),
                ('room', models.CharField(blank=True, max_length=300, null=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.building')),
                ('field', models.ManyToManyField(to='mainApp.field')),
                ('semester', models.ManyToManyField(null=True, to='mainApp.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('availability', models.CharField(choices=[('PUBLIC', 'for all users'), ('RESTRICTED', 'for me and my group-mates'), ('PRIVATE', 'only for me')], max_length=20)),
                ('type', models.CharField(choices=[('LINK', 'link'), ('FILE', 'file')], default='LINK', max_length=100)),
                ('link', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='files')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.course')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.field')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=6)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
