# Generated by Django 5.1.7 on 2025-05-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='G1_subject',
            field=models.ManyToManyField(blank=True, related_name='G1', to='mainApp.maturasubject'),
        ),
        migrations.AddField(
            model_name='field',
            name='G2_subject',
            field=models.ManyToManyField(blank=True, related_name='G2', to='mainApp.maturasubject'),
        ),
        migrations.AddField(
            model_name='field',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='specialization',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('STACJONARNE', 'for all users'), ('NIESTACJONARNE', 'for me and my group-mates')], default='stacjonarne', max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='eCoPCKBeb4acYwQqDEZrnQ4yTGjQZgMX', max_length=300),
        ),
    ]
