# Generated by Django 5.1.7 on 2025-05-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_field_g1_subject_field_g2_subject_field_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='faculty',
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='VBBC4IgfDZUlapTRTzpe58JrzMIFdw2I', max_length=300),
        ),
        migrations.AddField(
            model_name='field',
            name='faculty',
            field=models.ManyToManyField(to='mainApp.faculty'),
        ),
    ]
