# Generated by Django 5.1.7 on 2025-04-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_faculty_field_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='isRead',
            field=models.BooleanField(default=False),
        ),
    ]
