# Generated by Django 5.1.7 on 2025-05-06 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_remove_field_faculty_alter_group_code_field_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='field_by_year',
        ),
        migrations.AddField(
            model_name='fieldbyyear',
            name='semesters',
            field=models.ManyToManyField(to='mainApp.semester'),
        ),
        migrations.AddField(
            model_name='fieldbyyear',
            name='students',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='semester',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.ManyToManyField(to='mainApp.semester'),
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='Fgwa8wkcdjEoW5pFGIQHvHy1KXGmfFMY', max_length=300),
        ),
        migrations.CreateModel(
            name='CourseGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=4)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('all_studies', models.ManyToManyField(to='mainApp.fieldbyyear')),
                ('completed_semesters', models.ManyToManyField(related_name='completed_semesters', to='mainApp.semester')),
                ('current_semesters', models.ManyToManyField(related_name='current_semesters', to='mainApp.semester')),
                ('grades', models.ManyToManyField(to='mainApp.coursegrade')),
            ],
        ),
    ]
