# Generated by Django 5.1.7 on 2025-04-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_notification_isread'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='formula',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
