# Generated by Django 5.1.7 on 2025-04-07 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_field_formula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('min_threshold', models.IntegerField(default=0)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.field')),
            ],
        ),
    ]
