# Generated by Django 5.1.7 on 2025-04-10 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('availability', models.CharField(choices=[('PUBLIC', 'for all users'), ('RESTRICTED', 'for me and my group-mates'), ('PRIVATE', 'only for me')], max_length=20)),
                ('link', models.URLField()),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.field')),
            ],
        ),
    ]
