# Generated by Django 5.1.7 on 2025-05-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_group_code_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='additional_info',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='ECTS',
            new_name='ects',
        ),
        migrations.AddField(
            model_name='field',
            name='level',
            field=models.CharField(default='I stopień', max_length=300),
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='VQViEpEYCSFqpSUWttGslSHUvbdDQmec', max_length=300),
        ),
    ]
