# Generated by Django 5.1.7 on 2025-05-12 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_rename_additional_info_course_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.building'),
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='kuARcQDjvt7H3rUddWds8YdajDfdJj5v', max_length=300),
        ),
    ]
