# Generated by Django 5.1.7 on 2025-04-10 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('ECTS', models.IntegerField(default=1)),
                ('test_type', models.CharField(default='egzamin', max_length=300)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('lecturer', models.CharField(blank=True, max_length=300, null=True)),
                ('field', models.ManyToManyField(to='mainApp.field')),
            ],
        ),
        migrations.AddField(
            model_name='source',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.course'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('color', models.CharField(max_length=300)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('recurrent', models.BooleanField(default=False)),
                ('recurrency_details', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FieldByYear',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.field')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('ECTS_required', models.IntegerField(default=30)),
                ('field_by_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.fieldbyyear')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ManyToManyField(to='mainApp.semester'),
        ),
    ]
