# Generated by Django 5.1.7 on 2025-05-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_course_place_alter_group_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='room',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='ig3ANRCgf00zCtJSH1qVhMMEpMI9JGMe', max_length=300),
        ),
    ]
