# Generated by Django 5.1.7 on 2025-04-10 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_course_source_course_event_fieldbyyear_semester_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('code', models.CharField(default='meVSaeeEDivaYYOJTpOBXMj2DuSrFmaX', max_length=300)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fieldByYear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.fieldbyyear')),
            ],
        ),
    ]
