# Generated by Django 5.1.7 on 2025-04-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='source',
            name='type',
            field=models.CharField(choices=[('LINK', 'link'), ('FILE', 'file')], default='LINK', max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='U0CKylzB5wKTkAndrlmQbN6Ewza3C3x3', max_length=300),
        ),
        migrations.AlterField(
            model_name='source',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
