# Generated by Django 5.1.7 on 2025-05-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_course_room_alter_group_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='place',
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='5Dud9uBPmburtvmTkx1jmNXtyDFBNC4R', max_length=300),
        ),
    ]
