# Generated by Django 5.1.7 on 2025-05-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_remove_course_place_alter_group_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='GuLLqT3ktijstNKG3GvoSFHG5bO2Y3cW', max_length=300),
        ),
    ]
