# Generated by Django 5.1.7 on 2025-04-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_source_file_source_type_alter_group_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='oMgaT3vvSFSyZ9H3vEFnA1swygJg7m3D', max_length=300),
        ),
        migrations.AlterField(
            model_name='source',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='../../files'),
        ),
    ]
