# Generated by Django 5.1.7 on 2025-05-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_alter_group_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='room',
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='9leYTVVbqNK5OquB5eZL8QqOiKKQjVbJ', max_length=300),
        ),
    ]
