# Generated by Django 5.1.7 on 2025-04-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_alter_group_code_alter_source_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='SnhMGAuwPcNatTWbCGBMC3aVFbuDiIJz', max_length=300),
        ),
        migrations.AlterField(
            model_name='source',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
