# Generated by Django 5.1.7 on 2025-04-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_alter_group_code_alter_source_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='ywny47615BKSZTbFT3bQ6GiUoZoWgsKK', max_length=300),
        ),
    ]
