# Generated by Django 5.1.7 on 2025-05-13 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_group_description_group_ispublic_group_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='limit',
            field=models.IntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='kcmdyqwkGj7Rh4UXimV7djDJLp0gR3Gc', max_length=300),
        ),
        migrations.AlterField(
            model_name='group',
            name='fieldByYear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.fieldbyyear'),
        ),
    ]
