# Generated by Django 5.1.7 on 2025-04-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_alter_appuser_profile_picture_alter_group_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaturaSubject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='field',
            name='formula',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='bT3cblZKvR4lkn6LlTF4uEwngOLOMhy8', max_length=300),
        ),
        migrations.AddField(
            model_name='field',
            name='G1_subject',
            field=models.ManyToManyField(blank=True, related_name='G1', to='mainApp.maturasubject'),
        ),
        migrations.AddField(
            model_name='field',
            name='G2_subject',
            field=models.ManyToManyField(blank=True, related_name='G2', to='mainApp.maturasubject'),
        ),
    ]
