# Generated by Django 5.1.7 on 2025-04-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_maturasubject_alter_field_formula_alter_group_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maturasubject',
            name='level',
            field=models.CharField(choices=[('PD', 'podstawowy'), ('ROZ', 'rozszerzony')], default='ROZ', max_length=300),
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='df61YKkbo2HprnDb2zxeTyEnz7W7XHn2', max_length=300),
        ),
    ]
