# Generated by Django 5.1.7 on 2025-05-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_group_limit_alter_group_code_alter_group_fieldbyyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='PnJlZOLpVDpVaQRGjiyEae9KSoM2tu4a', max_length=300),
        ),
    ]
