# Generated by Django 5.1.7 on 2025-05-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_group_archived_alter_group_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='beRenrL6Y0mJBKueCvRNn0K2qFj9fbLp', max_length=300),
        ),
    ]
