# Generated by Django 5.1.7 on 2025-05-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_alter_group_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='1QAtBBkk57jM9il3K7YzwxPY6DMmZhv8', max_length=300),
        ),
    ]
