# Generated by Django 5.1.7 on 2025-05-13 12:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_alter_group_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='Z7h7Cvcf13PtKycSPdr2LySFD8HzyJ4j', max_length=300),
        ),
    ]
