# Generated by Django 5.1.7 on 2025-05-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_group_date_created_alter_group_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='isOfficial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='ZnLN7PrycqKfnI3j8AMO3iaS3T6nxgP0', max_length=300),
        ),
    ]
