# Generated by Django 5.1.7 on 2025-05-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_group_isofficial_alter_group_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='AGr753BgClBfINAI3BSuJ1CrJYZjGmgo', max_length=300),
        ),
        migrations.AlterField(
            model_name='group',
            name='limit',
            field=models.IntegerField(blank=True, default=150, null=True),
        ),
    ]
