# Generated by Django 5.1.7 on 2025-05-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_alter_group_code_alter_group_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='2Kw1AbWtCTzHkhdjrdsUIMUoXaHAZkIw', max_length=300),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
