# Generated by Django 5.1.7 on 2025-05-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0021_attachment_alter_group_code_remove_news_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='TWJ68TUQvqqQtH7BUc07tVwKEXYwcukA', max_length=300),
        ),
    ]
