# Generated by Django 5.1.7 on 2025-05-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0022_source_description_alter_group_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('stacjonarne', 'stacjonarne'), ('niestacjonarne', 'niestacjonarne')], default='stacjonarne', max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='1icLPjJeWvy3oF4xdSR75eTS1Ss5kcbH', max_length=300),
        ),
    ]
