# Generated by Django 5.1.7 on 2025-05-21 23:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0023_alter_field_type_alter_group_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='group',
            name='coverImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='group',
            name='moderators',
            field=models.ManyToManyField(related_name='moderators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='recentActivity',
            field=models.ManyToManyField(related_name='recentActivity', to='mainApp.event'),
        ),
        migrations.AddField(
            model_name='group',
            name='rules',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='DYMahnqDjGnPIj6fmyJ55dpmZDGKifAJ', max_length=300),
        ),
    ]
