# Generated by Django 5.1.7 on 2025-05-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0024_group_avatar_group_coverimage_group_moderators_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='emGUij6cubhgCIVldTLC0sorDV3iWbyG', max_length=300),
        ),
    ]
