# Generated by Django 5.1.7 on 2025-05-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0025_appuser_is_active_alter_group_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='is_active',
            new_name='is_online',
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='daFYbHtZ7V9vPwz1l1vDKEmxSCQRirMj', max_length=300),
        ),
    ]
