# Generated by Django 5.1.7 on 2025-05-22 00:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0026_rename_is_active_appuser_is_online_alter_group_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='9m8v6mhTQoVIgZ3R3DNtJ4aFzozVuI7w', max_length=300),
        ),
        migrations.AlterField(
            model_name='group',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='recentActivity',
            field=models.ManyToManyField(blank=True, related_name='recentActivity', to='mainApp.event'),
        ),
    ]
