# Generated by Django 5.1.7 on 2025-05-22 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0027_alter_group_code_alter_group_moderators_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='group_files_avatar'),
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='5Hu8d2QuitfwrJv1RgSg7pxSSAaSYGx6', max_length=300),
        ),
        migrations.AlterField(
            model_name='group',
            name='coverImage',
            field=models.ImageField(blank=True, null=True, upload_to='group_files_cover'),
        ),
    ]
