# Generated by Django 5.1.7 on 2025-05-30 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0029_alter_group_code_like_post_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='O6RV50GeVXPgccwpJN7SMXupQMnlqnze', max_length=300),
        ),
    ]
