# Generated by Django 5.1.7 on 2025-05-30 12:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0030_source_group_alter_group_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='p6wND8UBCjUxnKNEx2xRkiKHBHdcKk6Q', max_length=300),
        ),
    ]
