# Generated by Django 5.1.7 on 2025-05-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0031_appuser_joined_at_alter_group_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('GROUP EVENT', 'group event'), ('USER EVENT', 'user event'), ('FIELD EVENT', 'field by year event')], default='USER EVENT', max_length=300),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('NORMAL', 'normal'), ('GROUP INVITATION', 'group invitation')], default='NORMAL', max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='2g6HXnfJhJJENytPveGhSEvQebFxwXuN', max_length=300),
        ),
    ]
