# Generated by Django 5.1.7 on 2025-05-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0032_event_type_notification_type_alter_group_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='wxDQmQFX5cIcaXu14Ig7cxF2xq43MN44', max_length=300),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time_triggered',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
