# Generated by Django 5.1.7 on 2025-05-30 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0034_notification_isanswered_alter_group_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='KLEEkJCbd3tylNczSgUMjoxCaAIdGzSl', max_length=300),
        ),
    ]
