# Generated by Django 5.1.7 on 2025-06-02 23:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0035_notification_group_alter_group_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='student_email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='jcsUi2eAoxOTCldJ5KE7hn2GH6OTbavP', max_length=300),
        ),
    ]
