# Generated by Django 5.1.7 on 2025-06-02 23:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0036_appuser_student_email_alter_appuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='TEe39U7mdpfFYtCKekv7RyOA9WjxTtua', max_length=300),
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email do weryfikacji')),
                ('verification_code', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Kod weryfikacyjny')),
                ('verification_type', models.CharField(choices=[('registration', 'Rejestracja konta'), ('password_reset', 'Reset hasła'), ('email_change', 'Zmiana adresu email')], default='registration', max_length=20, verbose_name='Typ weryfikacji')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('expires_at', models.DateTimeField(verbose_name='Data wygaśnięcia')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Czy zweryfikowano')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Data weryfikacji')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Weryfikacja email',
                'verbose_name_plural': 'Weryfikacje email',
                'ordering': ['-created_at'],
            },
        ),
    ]
