# Generated by Django 5.1.7 on 2025-06-03 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0037_alter_group_code_emailverification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='hf4xwMydhK9hx0rXoCKptPA9OpPLJcky', max_length=300),
        ),
    ]
