# Generated by Django 5.1.7 on 2025-06-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0038_remove_verificationcode_user_alter_group_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(to='mainApp.attachment'),
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='ZoHyUekqz7BfOukRuPJos5HK7wflhOpG', max_length=300),
        ),

    ]
