# Generated by Django 5.1.7 on 2025-06-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0038_remove_verificationcode_user_alter_group_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationcode',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(to='mainApp.attachment'),
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='NM6zUqc3yWx4S6Px8QS9KS0xwj8nKW2e', max_length=300),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['email', 'verification_code'], name='mainApp_ema_email_c52444_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['expires_at'], name='mainApp_ema_expires_ef4bc5_idx'),
        ),
        migrations.DeleteModel(
            name='VerificationCode',
        ),
    ]
