# Generated by Django 5.1.7 on 2025-06-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0039_remove_verificationcode_user_post_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='IZaE5AC8flu8O8SVHya5OQHvKLWjX9pJ', max_length=300),
        ),
    ]
