# Generated by Django 5.1.7 on 2025-06-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0041_remove_comment_likes_remove_post_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='NxMuacZbo3UVKLpl9brpemAS0RiQiJaj', max_length=300),
        ),
    ]
