# Generated by Django 5.1.7 on 2025-06-04 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0044_alter_group_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='recentActivity',
        ),
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(default='mquqpNxBYYJAQdBQMNdVUQTNZN3kkSow', max_length=300),
        ),
    ]
